### ISSUE TITLE
添加远程调用监控失败，提示“Grpc channel connect timeout.”

### ISSUE THREAD

**Issue by cwbcheng** [OpenSkywalking/skywalking-netcore#83]
services.AddSkyWalking(option =>
            {
                option.DirectServers = "My IP:11800";
                option.ApplicationCode = "Com.Ejsino.WebApi.ServiceGateway";
            });

2018-09-18 11:07:49,137 [13] INFO  Com.Ejsino.WebApi.ServiceGateway.Startup - Grpc channel connect timeout. Reached deadline.
warn: SkyWalking.Remote.GrpcConnection[0]
      Grpc channel connect timeout. Reached deadline.
2018-09-18 11:08:09,205 [14] INFO  Com.Ejsino.WebApi.ServiceGateway.Startup - Grpc channel connect timeout. Reached deadline.

**Comment by liuhaoyang** [comment]
Check if the `SkyWalking Collector` is started successfully.

**Comment by cwbcheng** [comment]
> Check if the `SkyWalking Collector` is started successfully.

成功运行了。

services.AddSkyWalking(option =>
            {
                option.DirectServers = "localhost:11800";
                option.ApplicationCode = "Com.Ejsino.WebApi.ServiceGateway";
            });
我在远程服务器上运行连接localhost的demo，成功连接，在dashboard上也可以看到。

我在本地机器运行连接远程服务器IP的demo，提示Grpc连接超时。

**Comment by liuhaoyang** [comment]
@cwbcheng Modify your collector config(`config/application.yml`), change `agent_gRPC:gRPC:host` to the real network address (default is localhost)
```
agent_gRPC:
  gRPC:
    # OS real network IP(binding required), for agent to uplink data(trace/metrics) to collector. agent--(gRPC)--> collector
    host: real-network    
    port: 11800
```
